=== totalcms/cms/resources/schemas/auth.json
{
	"$schema"     : "https://json-schema.org/draft/2020-12/schema",
	"$id"         : "https://www.totalcms.co/schemas/auth.json",
	"id"          : "auth",
	"type"        : "object",
	"description" : "A schema for a Total CMS user accounts and authentication",
	"formgrid"    : "active active\nid id\nimage image\nname name\nemail email\npassword password\ngroups loginCount\nexpiration created\nmaxLoginCount lastlogin",
	"properties"  : {
		"active": {
			"type"    : "boolean",
			"label"   : "Active",
			"help"    : "Mark this user as active",
			"field"   : "toggle",
			"factory" : "boolean"
		},
		"id": {
			"$ref"     : "https://www.totalcms.co/schemas/properties/slug.json",
			"label"    : "ID",
			"help"     : "A unique id for this user. If left blank, it will be auto-generated from the email address.",
			"field"    : "id",
			"factory"  : "slug",
			"settings" : { "autogen" : "${email}" }
		},
		"image": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/image.json",
			"label"   : "Profile Image",
			"help"    : "Profile image for this user",
			"field"   : "image",
			"factory" : "imageShapes(512,512)"
		},
		"name": {
			"type"    : "string",
			"label"   : "Name",
			"help"    : "Full name of this user",
			"field"   : "text",
			"factory" : "name"
		},
		"email": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/email.json",
			"label"   : "Email",
			"help"    : "Email address for this user",
			"field"   : "email",
			"factory" : "email",
			"unique"  : true
		},
		"password": {
			"$ref"        : "https://www.totalcms.co/schemas/properties/password.json",
			"label"       : "Password",
			"help"        : "Password for this user",
			"placeholder" : "Enter password",
			"field"       : "password",
			"factory"     : "password",
			"minLength"   : 4,
			"settings"    : {
				"minlength"          : 4,
				"confirmPlaceholder" : "Confirm password"
			}
		},
		"groups": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/list.json",
			"label"   : "Groups",
			"help"    : "Groups this user belongs to",
			"field"   : "list",
			"settings" : {
				"accessGroupOptions"    : true,
				"duplicateItemsAllowed" : false,
				"addChoices"            : false
			}
		},
		"expiration": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/date.json",
			"label"   : "Expiration Date",
			"help"    : "Account expiration date",
			"field"   : "date"
		},
		"maxLoginCount": {
			"type"    : "number",
			"label"   : "Maximum Login Count",
			"help"    : "The maximum number of times this user can login",
			"field"   : "number",
			"default" : 0
		},
		"loginCount": {
			"type"    : "number",
			"label"   : "Login Count",
			"help"    : "Number of times this user has logged in",
			"field"   : "number",
			"default" : 0,
			"settings" : { "readonly" : true }
		},
		"created": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/date.json",
			"label"   : "Creation Date",
			"help"    : "Date this user was created",
			"field"   : "datetime",
			"settings": { "onCreate" : true, "readonly": true }
		},
		"lastlogin": {
			"$ref"    : "https://www.totalcms.co/schemas/properties/date.json",
			"label"   : "Last Login",
			"help"    : "Last time this user logged in",
			"field"   : "datetime",
			"factory" : "iso8601",
			"settings" : { "readonly" : true }
		}
	},
	"required": [
		"id",
		"created",
		"email",
		"password"
	],
	"index": [
		"active",
		"image",
		"name",
		"email",
		"groups",
		"loginCount",
		"maxLoginCount",
		"lastlogin",
		"expiration",
		"created",
		"id"
	]
}

=== totalcms/cms/tests/tcms-data-fixtures/auth/blogger-user-test-com.json
{
    "id": "blogger-user-test-com",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "nodata": ""
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 0,
        "link": "",
        "mime": "",
        "name": "",
        "palette": [],
        "size": 0,
        "tags": [],
        "uploadDate": "2025-10-20T18:26:06-07:00",
        "width": 0
    },
    "name": "Blogger Test User",
    "email": "blogger-user@test.com",
    "password": "$2y$12$xf1qgTR.7pbm8Mbrwf7uSOvTZ\/k6JGDb1NfbLBOvldzYawe5roMUa",
    "groups": [
        "blogger"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 2,
    "created": "2025-10-20T00:00:00+00:00",
    "lastlogin": "2025-10-21T00:00:58-07:00"
}

=== totalcms/cms/tests/tcms-data/auth/admin.json
{
    "id": "admin",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "date": "2014-11-23T08:23:00+00:00",
            "make": "Apple",
            "camera": "iPhone 5",
            "lens": "iPhone 5 front camera 2.18mm f\/2.4",
            "focalLength": 2.18,
            "aperture": 2.4,
            "iso": 32,
            "shutterSpeed": "1\/40"
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 960,
        "link": "",
        "mime": "image\/jpeg",
        "name": "small_1193.jpg",
        "palette": [
            "#ecb48e",
            "#7d5050",
            "#889980",
            "#4a2d3b",
            "#b44248"
        ],
        "size": 107466,
        "tags": [],
        "uploadDate": "2025-02-18T14:08:00+00:00",
        "width": 960
    },
    "name": "Joe",
    "email": "joe@workmanmail.com",
    "password": "$2y$12$82qI5iWdb.0ICaGKw7flNOpSfJrZ44uYKjb.1LvH9FKFaVINuW0pq",
    "groups": [
        "admin"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 152,
    "created": "2025-02-18T14:07:00+00:00",
    "lastlogin": "2025-10-20T17:55:16-07:00"
}

=== totalcms/cms/tests/tcms-data-fixtures/auth/viewer-user-test-com.json
{
    "id": "viewer-user-test-com",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "nodata": ""
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 0,
        "link": "",
        "mime": "",
        "name": "",
        "palette": [],
        "size": 0,
        "tags": [],
        "uploadDate": "2025-10-20T18:05:53-07:00",
        "width": 0
    },
    "name": "Viewer Test User",
    "email": "viewer-user@test.com",
    "password": "$2y$12$xf1qgTR.7pbm8Mbrwf7uSOvTZ\/k6JGDb1NfbLBOvldzYawe5roMUa",
    "groups": [
        "viewer"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 2,
    "created": "2025-10-20T00:00:00+00:00",
    "lastlogin": "2025-10-21T00:01:23-07:00"
}

=== totalcms/cms/tests/tcms-data/auth/editor-user-test-com.json
{
    "id": "editor-user-test-com",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "nodata": ""
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 0,
        "link": "",
        "mime": "",
        "name": "",
        "palette": [],
        "size": 0,
        "tags": [],
        "uploadDate": "2025-10-20T21:40:56-07:00",
        "width": 0
    },
    "name": "Editor Test User",
    "email": "editor-user@test.com",
    "password": "$2y$12$xf1qgTR.7pbm8Mbrwf7uSOvTZ\/k6JGDb1NfbLBOvldzYawe5roMUa",
    "groups": [
        "editor"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 1,
    "created": "2025-10-20T00:00:00+00:00",
    "lastlogin": "2025-10-20T21:40:56-07:00"
}

=== totalcms/cms/tests/tcms-data/auth/limited-user-test-com.json
{
    "id": "limited-user-test-com",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "nodata": ""
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 0,
        "link": "",
        "mime": "",
        "name": "",
        "palette": [],
        "size": 0,
        "tags": [],
        "uploadDate": "2025-10-20T21:43:18-07:00",
        "width": 0
    },
    "name": "Limited Blogger Test User",
    "email": "limited-user@test.com",
    "password": "$2y$12$xf1qgTR.7pbm8Mbrwf7uSOvTZ\/k6JGDb1NfbLBOvldzYawe5roMUa",
    "groups": [
        "limited-blogger"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 1,
    "created": "2025-10-20T00:00:00+00:00",
    "lastlogin": "2025-10-20T21:43:18-07:00"
}

=== totalcms/cms/tests/tcms-data-fixtures/auth/admin-user-test-com.json
{
    "id": "admin-user-test-com",
    "active": true,
    "image": {
        "alt": "",
        "exif": {
            "nodata": ""
        },
        "featured": false,
        "focalpoint": {
            "x": 50,
            "y": 50
        },
        "height": 0,
        "link": "",
        "mime": "",
        "name": "",
        "palette": [],
        "size": 0,
        "tags": [],
        "uploadDate": "2025-10-20T18:00:48-07:00",
        "width": 0
    },
    "name": "Admin Test User",
    "email": "admin-user@test.com",
    "password": "$2y$12$xf1qgTR.7pbm8Mbrwf7uSOvTZ\/k6JGDb1NfbLBOvldzYawe5roMUa",
    "groups": [
        "admin"
    ],
    "expiration": "",
    "maxLoginCount": 0,
    "loginCount": 4,
    "created": "2025-10-20T00:00:00+00:00",
    "lastlogin": "2025-10-21T09:59:55-07:00"
}
